= Introduction

The Flex Template allows you to import a dataset into a Neo4j database through a Dataflow job, sourcing data from CSV files hosted in Google Cloud Storage buckets.
It also allows you to manipulate and transform the data at various steps of the import.
You can use the template for both first-time and incremental imports.

This guide walks you through how to import an example dataset into a Neo4j database using a Dataflow job. It also provides a public dataset you can experiment with, before you go on and create an import job for your own dataset.

[NOTE]
To import data from Google BigQuery, check out the xref:dataflow-bigquery::index.adoc[Dataflow Flex Template for BigQuery to Neo4j].

[NOTE]
All Google-related resources (Cloud project, Cloud Storage buckets, Dataflow job) should either belong to the same account, or to one which the Dataflow job has permissions to access.

[TIP]
This is not the only tool to import CSV files into Neo4j. You may also want to check out the Cypher clause link:https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`], or parse the CSVs in your favorite language and use one of link:https://neo4j.com/docs/create-applications/[Neo4j's client libraries (drivers)] to insert the data into the database.
