:page-role: beta

= Dataflow Flex Template for Google Cloud to Neo4j

The Flex Template allows to import a dataset into a Neo4j database through a Dataflow job, sourcing data from CSV files hosted in Google Cloud Storage buckets.
It also allows to manipulate and transform the data at various steps of the import.
You can use the template for both first-time and incremental imports.

This guide walks you through how to import an example dataset into a Neo4j database using a Dataflow job. It also provides a public dataset you can experiment with, before you go on and create an import job for you own dataset.

[NOTE]
To import data from Google BigQuery, checkout the link:https://neo4j.com/docs/dataflow-bigquery/[Dataflow Flex Template for BigQuery to Neo4j].


[discrete]
== Things you will need

Here is the high-level list of the things you will need throughout the tutorial.

- A running Neo4j instance
- A Google account and a Google Cloud project
- A link:https://console.cloud.google.com/storage/[Google Cloud Storage] bucket
- A dataset to import, in the form of CSV files
- A link:https://console.cloud.google.com/dataflow/[Google Dataflow] project

Head to xref:prerequisites.adoc[] to find more details about each of them.

[NOTE]
All Google-related resources (Cloud project, Cloud Storage buckets, Dataflow job) should either belong to the same account, or to one which the Dataflow job has permissions to access.

[TIP]
This is not the only tool to import CSV files into Neo4j. You may also want to check out the Cypher clause link:https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`], or parse the CSVs in your favorite language and use one of link:https://neo4j.com/docs/create-applications/[Neo4j's client libraries (drivers)] to insert the data into the database.
