= Prerequisites

include::{common}:partial$prerequisites.adoc[tags=intro]

include::{common}:partial$prerequisites.adoc[tags=neo4j]

include::{common}:partial$prerequisites.adoc[tags=gcs-bucket]

include::{common}:partial$prerequisites.adoc[tags=connection-info]


== Dataset to import

You need a dataset that you want to import into Neo4j.
This should consist of a number of CSV files located in your Google Cloud Storage bucket.
This guide provides you with a set of CSV files to get started with.

Source CSV files must fulfill some constraints:

- **They should not contain empty rows.**
- **They should not contain a header row.** +
Specify column names in the source object definition, and leave only data rows in the files. A CSV with a header row will result in an extra imported entity, with the column names as data values.

[TIP]
Since you are moving data from a relational database into a graph database, **the data model is likely to change**.
Checkout link:https://neo4j.com/docs/getting-started/data-modeling/guide-data-modeling/[Graph data modeling guidelines] to learn how to model for graph databases.


include::{common}:partial$prerequisites.adoc[tags=dataflow-job]

