:target_property_type-valid-values-extra: Each property type (except byte_array) is also available in its "_array" form (i.e. date_array, string_array, etc) for BigQuery "repeated" column types.
:page-toclevels: 3

= Create a job specification file


include::{common}:partial$job-specification.adoc[tags=intro]



include::{common}:partial$job-specification.adoc[tags=full-example]

[source, json]
----
include::example$bigquery-movies-jobspec.json[]
----



include::{common}:partial$job-specification.adoc[tags=configuration]


[#sources]
== Sources

The `sources` section contains the definitions of the data sources, as a list. As a rough guideline, you can think `+one table <=> one source+`. The importer will take the data surfaced by the sources and make it available to the targets, which will eventually map it into Neo4j.

.Source object specification and its defaults
[source, json]
----
{
  "type": "bigquery",
  "name": "<sourceName>",
  "query": "<bigQuerySqlQuery>",
  "query_temp_project": "<projectName>",
  "query_temp_dataset": "<datasetName>"
}
----

- `type` (string) -- `bigquery`.
- `name` (string) -- A human-friendly label for the source (unique among all names; may not contain spaces). You will use this to reference the source from other parts of the specification file.
- `query` (string) -- The dataset to extract from BigQuery, as an SQL query. Notice that:

  1. the source table can have more columns than what you select in the query;
  2. multiple targets can use the same source, potentially filtering it for a different subset of columns.

- `query_temp_project` (string, optional) The Google Cloud project to store temporary query results (defaults to the current project).
- `query_temp_dataset` (string, optional) The BigQuery dataset to store temporary query results (defaults to a new temporary dataset).

[IMPORTANT]
If you set `query_temp_project`, you must also specify `query_temp_dataset`. +
You can specify `query_temp_dataset` alone; the template then uses the current project. +
If neither is set, the template uses the current project and create its own datasets for temporary processing.

[WARNING]
Columns of type `BIGNUMERIC`, `GEOGRAPHY`, `JSON`, `INTERVAL` and `STRUCT` are not supported.

[#source-full-example]
=== Example
.An example of a source object to import rows from a `persons` table
[source, json]
----
{
  "type": "bigquery",
  "name": "persons",
  "query": "SELECT person_tmdbId, name, bornIn, born, died FROM team-connectors-dev.movies.persons"
}
----


include::{common}:partial$job-specification.adoc[tags=targets]

include::{common}:partial$job-specification.adoc[tags=transformations]

include::{common}:partial$job-specification.adoc[tags=actions]

include::{common}:partial$job-specification.adoc[tags=variables]
