:target_property_type-valid-values-extra: Each property type (except byte_array) is also available in its "_array" form (i.e. date_array, string_array, etc) for BigQuery "repeated" column types.

= Create a job specification file


include::{common}:partial$job-specification.adoc[tags=intro]


[#full-example]
.A full job specification example
====
Here below is an example job specification file that works out of the box to import the publicly-available `movies` dataset.

The next sections break it down and provide in-context information for each part.
We recommend reading this guide side by side with the job specification example.

[source, json]
----
include::example$bigquery-movies-jobspec.json[]
----
====


include::{common}:partial$job-specification.adoc[tags=configuration]


[#sources]
== Sources

The `sources` section contains the definitions of the data sources, as a list. As a rough guideline, you can think `+one table <=> one source+`. The importer will take the data surfaced by the sources and make it available to the targets, which will eventually map it into Neo4j.

.Source object specification and its defaults
[source, json]
----
{
  "type": "bigquery",
  "name": "<sourceName>",
  "query": "<bigquerySqlQuery>"
}
----

- `type` (string) -- `bigquery`.
- `name` (string) -- A human-friendly label for the source (unique among all names; may not contain spaces). You will use this to reference the source from other parts of the specification file.
- `query` (string) -- The dataset to extract from BigQuery, as an SQL query. Notice that:

  1. the source table can have more columns than what you select in the query;
  2. multiple targets can use the same source, potentially filtering it for a different subset of columns.

[WARNING]
Columns of type `BIGNUMERIC`, `GEOGRAPHY`, `JSON`, `INTERVAL` and `STRUCT` are not supported.


include::{common}:partial$job-specification.adoc[tags=targets]

include::{common}:partial$job-specification.adoc[tags=transformations]

include::{common}:partial$job-specification.adoc[tags=actions]

include::{common}:partial$job-specification.adoc[tags=variables]
